---
driver:
  name: vagrant
  require_chef_omnibus: 12.13.37

provisioner:
  name: chef_zero_scheduled_task

transport:
  name: winrm
  elevated: true
verifier:
  name: inspec

platforms:
  - name: windows-2012r2
  
suites:
  - name: default
    run_list:
      - recipe[webappwindows::default]
    attributes:
      sql_server:
        sysadmins: ['vagrant']
