---
driver:
  name: vagrant

provisioner:
  name: chef_zero_scheduled_task

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
  
suites:
  - name: default
    run_list:
      - recipe[settings::default]
    attributes:
